services:
  db:
    image: postgres:16 # PostgreSQL 16の公式イメージ
    container_name: ec-training_postgres_16
    environment:
      POSTGRES_USER: developer # デフォルトのユーザー名
      POSTGRES_PASSWORD: 1234 # デフォルトのユーザーパスワード
      POSTGRES_DB: ec-training # デフォルトで作成されるデータベース名
    ports:
      - "5432:5432" # PostgreSQLのデフォルトポート
    volumes:
      - pgdata:/var/lib/postgresql/data # データの永続化ボリューム
      - ./db:/docker-entrypoint-initdb.d

volumes:
  pgdata:
    driver: local # ローカルストレージにデータを保存
