services:
  db:
    image: postgres:16 # PostgreSQL 16の公式イメージ
    container_name: ${CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # デフォルトのユーザー名
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # デフォルトのユーザーパスワード
      POSTGRES_DB: ${POSTGRES_DB} # デフォルトで作成されるデータベース名
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - "${PGPORT}:5432" # PostgreSQLのデフォルトポート
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/test_data:/test_data
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
  pgdata:
    driver: local # ローカルストレージにデータを保存
